- name: Configure Prometheus and Alertmanager
  hosts: prometheus
  become: yes
  roles:
    - prometheus
    - node_exporter

- name: Configure Grafana
  hosts: grafana
  roles:
    - grafana
    - node_exporter
