- name: Ensure Alertmanager configuration directory exists
  ansible.builtin.file:
    path: /etc/alertmanager
    state: directory
    mode: '0755'
  become: yes

- name: Deploy Alertmanager configuration
  ansible.builtin.template:
    src: alertmanager.yml.j2
    dest: /etc/alertmanager/alertmanager.yml
    mode: '0644'
  become: yes

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  become: yes

- name: Ensure Alertmanager service is running
  ansible.builtin.systemd:
    name: alertmanager
    state: started
    enabled: yes
  become: yes
