- name: Install Prometheus
  ansible.builtin.get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.31.2/prometheus-2.31.2.linux-amd64.tar.gz
    dest: /tmp/prometheus.tar.gz

- name: Extract Prometheus
  ansible.builtin.unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /usr/local/bin
    remote_src: yes

- name: Install Alertmanager
  ansible.builtin.get_url:
    url: https://github.com/prometheus/alertmanager/releases/download/v0.23.0/alertmanager-0.23.0.linux-amd64.tar.gz
    dest: /tmp/alertmanager.tar.gz

- name: Extract Alertmanager
  ansible.builtin.unarchive:
    src: /tmp/alertmanager.tar.gz
    dest: /usr/local/bin
    remote_src: yes

- name: Create Prometheus service
  ansible.builtin.copy:
    dest: /etc/systemd/system/prometheus.service
    content: |
      [Unit]
      Description=Prometheus
      After=network.target

      [Service]
      ExecStart=/usr/local/bin/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/var/lib/prometheus
      Restart=always

      [Install]
      WantedBy=multi-user.target

- name: Create Alertmanager service
  ansible.builtin.copy:
    dest: /etc/systemd/system/alertmanager.service
    content: |
      [Unit]
      Description=Alertmanager
      After=network.target

      [Service]
      ExecStart=/usr/local/bin/alertmanager --config.file=/etc/alertmanager/alertmanager.yml
      Restart=always

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd and start services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - prometheus
    - alertmanager
